"""Zero-based Modbus register offsets and protocol values.

Every offset in this module and in ``configs/modbus.yaml`` is a zero-based
Modbus holding-register address.  PLC engineering software may display a
one-based address or map it to a Mitsubishi D register separately.
"""

from __future__ import annotations

from enum import IntEnum, IntFlag


PLC_TO_PC_START = 100
PLC_TO_PC_COUNT = 20
PC_TO_PLC_START = 120
PC_TO_PLC_COUNT = 30


class PlcRegister(IntEnum):
    CONTROL_WORD = 100
    REQUESTED_RECIPE_ID = 101
    REQUESTED_RECIPE_REV = 102
    RECIPE_CHANGE_SEQ_LO = 103
    RECIPE_CHANGE_SEQ_HI = 104
    LINE_SPEED_X100 = 105
    LINE_STATE = 106
    TRIGGER_SEQ_LO = 107
    TRIGGER_SEQ_HI = 108
    RESULT_ACK_SEQ_LO = 109
    RESULT_ACK_SEQ_HI = 110
    HEARTBEAT = 111
    FAULT_CODE = 112
    COMMAND_CODE = 113
    COMMAND_SEQ = 114
    PRODUCT_LENGTH_MM = 115


class PcRegister(IntEnum):
    STATUS_WORD = 120
    ACTIVE_RECIPE_ID = 121
    ACTIVE_RECIPE_REV = 122
    RECIPE_ACK_SEQ_LO = 123
    RECIPE_ACK_SEQ_HI = 124
    RESULT_SEQ_LO = 125
    RESULT_SEQ_HI = 126
    RESULT_CODE = 127
    NG_CAMERA_MASK = 128
    FUSED_SCORE_X10000 = 129
    CAM0_SCORE_X10000 = 130
    CAM1_SCORE_X10000 = 131
    CAM2_SCORE_X10000 = 132
    CAM3_SCORE_X10000 = 133
    INFERENCE_TIME_MS = 134
    CAMERA_READY_MASK = 135
    MODEL_READY_MASK = 136
    HEARTBEAT = 137
    VISION_ERROR_CODE = 138
    VISION_WARNING_CODE = 139
    INFERENCE_QUEUE_DEPTH = 140
    DROPPED_TRIGGER_COUNT_LO = 141
    DROPPED_TRIGGER_COUNT_HI = 142
    MISSING_FRAME_COUNT_LO = 143
    MISSING_FRAME_COUNT_HI = 144
    PROCESSED_COUNT_LO = 145
    PROCESSED_COUNT_HI = 146
    COMMAND_ACK_SEQ = 147


class PlcControlBits(IntFlag):
    INSPECTION_ENABLED = 1 << 0
    BYPASS_REQUESTED = 1 << 1
    SAVE_TRAINING_IMAGES = 1 << 2
    MAINTENANCE_MODE = 1 << 3
    MANUAL_INSPECTION_REQUEST = 1 << 4
    PRODUCTION_RUNNING = 1 << 5


class PcStatusBits(IntFlag):
    APPLICATION_ALIVE = 1 << 0
    ALL_CAMERAS_READY = 1 << 1
    ALL_MODELS_READY = 1 << 2
    REQUESTED_RECIPE_LOADED = 1 << 3
    INSPECTION_READY = 1 << 4
    INSPECTION_BUSY = 1 << 5
    RESULT_PENDING = 1 << 6
    WARNING_ACTIVE = 1 << 7
    FAULT_ACTIVE = 1 << 8
    BYPASS_ACTIVE = 1 << 9
    TRAINING_IMAGE_COLLECTION_ACTIVE = 1 << 10
    COMMUNICATION_DEGRADED = 1 << 11


class LineState(IntEnum):
    STOPPED = 0
    SETUP = 1
    AUTOMATIC_PRODUCTION = 2
    PRODUCT_CHANGEOVER = 3
    MACHINE_FAULT = 4
    MAINTENANCE = 5


class PlcCommand(IntEnum):
    NONE = 0
    RESET_VISION_ERROR = 1
    RESET_INSPECTION_COUNTERS = 2
    RELOAD_ACTIVE_RECIPE = 3
    RELOAD_MODELS = 4
    SAVE_DIAGNOSTIC_IMAGES = 5
    RESTART_CAMERA_ACQUISITION = 6


class ResultCode(IntEnum):
    NO_VALID_RESULT = 0
    OK = 1
    NG = 2
    INSPECTION_SYSTEM_ERROR = 3
    INSPECTION_BYPASSED = 4
    INSPECTION_TIMEOUT = 5
    RECIPE_MISMATCH = 6
    MISSING_CAMERA_FRAME = 7
    TRIGGER_SYNCHRONIZATION_ERROR = 8


class VisionErrorCode(IntEnum):
    NONE = 0
    MODBUS_CONNECTION_UNAVAILABLE = 100
    PLC_HEARTBEAT_TIMEOUT = 101
    INVALID_MODBUS_RESPONSE = 102
    REQUESTED_RECIPE_NOT_FOUND = 110
    RECIPE_REVISION_MISMATCH = 111
    RECIPE_CONFIGURATION_INVALID = 112
    MODEL_LOADING_FAILED = 113
    CAMERA_UNAVAILABLE = 120
    MISSING_CAMERA_FRAME = 121
    TRIGGER_SYNCHRONIZATION_FAILURE = 122
    RESULT_QUEUE_FULL = 130
    RESULT_ACK_TIMEOUT = 131
    INTERNAL_INSPECTION_EXCEPTION = 140


class VisionWarningCode(IntEnum):
    NONE = 0
    COMMUNICATION_RECOVERED = 200
    HIGH_INFERENCE_QUEUE_DEPTH = 201
    INFERENCE_SLOWER_THAN_CYCLE_TIME = 202
    RESULT_ACK_DELAYED = 203
    TRAINING_IMAGE_COLLECTION_ENABLED = 204